server:
  port: 8080 # 所有后端请求的入口
logging:
  level:
    # 强制将所有日志的根级别设置为 INFO（保证 INFO 及其以上级别输出）
    root: INFO
    # 将 Gateway 的核心日志级别设置为 DEBUG
    org.springframework.cloud.gateway: DEBUG
    # (可选) 将 Reactor Netty 的日志也设为 DEBUG，可以看到更底层的网络交互
    reactor.netty.http.client: DEBUG
    com.alibaba.nacos.client: DEBUG

    # 2025-09-27T15:33:55.811+08:00 DEBUG 24536 --- [naming.failover] com.alibaba.nacos.client.naming          : failover switch is not found, 00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00
    # API GATEWAY 在启动了之后一直出现上边的log，这是debug级别log，它只是告诉你：“我没有在配置中找到明确的故障转移开关，所以使用默认行为。”
    # 明确开启或关闭这个本地缓存机制，可以在你的 Gateway 项目 的配置中添加以下配置项：
    # 提高 Nacos 客户端日志级别，屏蔽 DEBUG 信息
    # com.alibaba.nacos: INFO 这个设定的时候没有生效 因为这个包名太宽泛，它只影响 com.alibaba.nacos 下的顶级类，不一定能覆盖到所有子包。
    com.alibaba.nacos.client.naming: INFO
    # 确保你的项目其它包仍使用 DEBUG 或所需的级别
    com.yourpackage.gateway: DEBUG
spring:
  application:
    name: api-gateway-rae
  config:
    import:
      # 引入共享配置
      - "nacos:shared-config-rae.yml"
  cloud:
    nacos:
      server-addr: 3.84.225.222:8848
      config:
        # 明确告诉 Nacos Config 默认的文件扩展名是 yml
        file-extension: yml
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: false # 开启基于服务发现的路由功能
          lower-case-service-id: true # 将服务名转为小写路径，e.g., user-service -> /user-service/**
      routes:
        - id: user_service_route
          uri: lb://user-service-rae # lb:// 表示从Nacos负载均衡地选择一个user-service实例
#          uri: http://192.168.31.186:8081
          predicates:
            - Path=/api/user/**,/api/auth/** # 匹配所有/api/user/开头的请求
#          filters:
#            - StripPrefix=2
#        - id: qa_service_route
#          uri: lb://qa-service
#          predicates:
#            - Path=/api/qa/**
      default-filters:
        # 配置默认的限流过滤器
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@ipKeyResolver}'
