server:
  port: 8080 # 所有后端请求的入口
logging:
  level:
    # 将 Gateway 的核心日志级别设置为 DEBUG
    org.springframework.cloud.gateway: DEBUG
    # (可选) 将 Reactor Netty 的日志也设为 DEBUG，可以看到更底层的网络交互
    reactor.netty.http.client: DEBUG
    com.alibaba.nacos.client: DEBUG
spring:
  application:
    name: api-gateway-rae
  config:
    import: "nacos:share-config-rae.yml"
  cloud:
    nacos:
      server-addr: 54.183.199.195:8848
      config:
        file-extension: yml
        group: DEFAULT_GROUP
      discovery:
        # server-addr: 54.183.199.195:8848
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        # ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP}
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: false # 开启基于服务发现的路由功能
          lower-case-service-id: true # 将服务名转为小写路径，e.g., user-service -> /user-service/**
          url-expression: "'http://' + serviceId.toLowerCase() + ':' + port"
      routes:
        - id: user_service_route
          uri: lb://user-service-rae # lb:// 表示从Nacos负载均衡地选择一个user-service实例
#          uri: http://192.168.31.186:8081
          predicates:
            - Path=/api/users/** # 匹配所有/api/users/开头的请求
          filters:
            - StripPrefix=2
        - id: qa_service_route
          uri: lb://qa-service-rae
          predicates:
            - Path=/api/qa/**
      # default-filters:
      #   - name: RequestRateLimiter
jwt:
  secret: 63ffbc2b8d13ad5180ed7ae7c67f18c85d86046732fc9ced6a02a9d50abb1a03
  expiration:
    ms: 86400000  # 这里是具体的过期时间（毫秒），对应Expiration的ms字段