services:

  postgre-db:
    image: postgres:14-alpine
    # --- 添加下面的 environment 部分 ---
    environment:
      POSTGRES_USER: postgres      # 使用您 application.yml 中的用户名
      POSTGRES_PASSWORD: root          # 使用您 application.yml 中的密码
      POSTGRES_DB: postgresql  # 创建您 application.yml 中指定的数据库
    # ------------------------------------
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always # 建议添加，确保容器失败后能自动重启
  
  api-gateway:
    build:
      context: ./backend-services
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Nacos 服务器的地址和端口
      - NACOS_SERVER_ADDR=54.183.199.195:8848
      # 当前环境的公网IP，用于服务注册
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=54.183.199.195
      # - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - user-service
      - qa-service
    networks:
      - ai-network

  user-service:
    build:
      context: ./backend-services
      dockerfile: user-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Nacos 服务器的地址和端口
      - NACOS_SERVER_ADDR=54.183.199.195:8848
      # 当前环境的公网IP，用于服务注册
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=54.183.199.195
      # - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - redis
    networks:
      - ai-network

  qa-service:
    build:
      context: ./backend-services
      dockerfile: qa-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      # Nacos 服务器的地址和端口
      - NACOS_SERVER_ADDR=54.183.199.195:8848
      # 当前环境的公网IP，用于服务注册
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=54.183.199.195
      # - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - redis
    networks:
      - ai-network

  frontend:
    build:
     context: ./fronted
     dockerfile: Dockerfile
    ports:
     - "3000:3000"
    depends_on:
      - api-gateway
      - user-service
      - qa-service
    networks:
      - ai-network

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: ai_qa_system
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - ai-network


networks:
  ai-network:
    driver: bridge

volumes:
  postgres-data:
