server:
  port: 8082
spring:
  application:
    name: qa-service-rae
  cloud:
    nacos:
      discovery:
        # server-addr: 54.183.199.195:8848
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP}
  data:
    redis:
      host: redis  # Docker 服务名
      port: 6379
  datasource:
    url: jdbc:postgresql://postgres:5432/ai_qa_system?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    # 将你的FeignClient接口所在的包路径设置为DEBUG
    # 假设 UserClient 在 com.ai.qa.qaservice.feign 包下
    com.ai.qa.qaservice.feign: DEBUG
chat:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
    key: AIzaSyD-V4KPeOzfVHRTJ0Com2xIysmbu2C66sw
gemini:
  api-key: AIzaSyD-V4KPeOzfVHRTJ0Com2xIysmbu2C66sw
GOOGLE_API_KEY:
  AIzaSyD-V4KPeOzfVHRTJ0Com2xIysmbu2C66sw