server:
  port: 8081
spring:
  application:
    name: user-service-rae
  cloud:
    nacos:
      discovery:
        # server-addr: 54.183.199.195:8848
        # ip: 54.183.199.195
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP}
  datasource:
    url: jdbc:postgresql://postgres:5432/postgresql?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: 63ffbc2b8d13ad5180ed7ae7c67f18c85d86046732fc9ced6a02a9d50abb1a03
  expiration:
    ms: 86400000  # 这里是具体的过期时间（毫秒），对应Expiration的ms字段